config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             skip: [:session, :password, :registration],
             controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: {
      registration: 'registrations'
    }, skip: :omniauth_callbacks

    root to: "events#index"

    resources :users, only: %i[show edit update]

    resources :events do
      resources :comments, only: %i[create destroy]
      resources :subscriptions, only: %i[create destroy]
      resources :photos, only: %i[create destroy]

      post :show, on: :member
    end
  end
  get '/politica', :to => redirect('/politica.html')
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  validates :event, presence: true
  validates :body, presence: true
  validates :user_name, presence: true, unless: -> { user.present? }

  def user_name
    if user.present?
      user.name
    else
      super
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event, only: %i[create destroy]
  before_action :set_comment, only: [:destroy]

  after_action :verify_authorized, only: [:destroy]

  def create
    @new_comment = @event.comments.build(comment_params)

    authorize @new_comment

    @new_comment.user = current_user

    if @new_comment.save
      NotifySubscribersJob.perform_later(@new_comment)
      redirect_to @event, notice: I18n.t('controllers.comments.created')
    else
      render 'events/show', alert: I18n.t('controllers.comments.error')
    end
  end

  def destroy
    authorize @comment
    message = { notice: I18n.t('controllers.comments.destroyed') }

    @comment.destroy!

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_comment
    @comment = @event.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_name)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="mb-2 card">
  <div class="card-body">
    <div class="comment-block d-flex align-items-center">
      <div class="user-block">
        <% if comment.user.present? %>
          <%= render partial: 'users/user', object: comment.user %>
        <% else %>
          <em><strong><%= comment.user_name %></strong></em>
        <% end %>
        <em><%= l comment.created_at, format: :short %></em>
      </div>
      <% if policy(comment).destroy? %>
        <%= button_to '❌', event_comment_path(comment.event, comment), method: :delete,
                      form: { data: { turbo_confirm: t('.destroy_confirm') } }, title: t('views.buttons.delete'), class: 'btn
                      btn-outline' %>
      <% end %>
    </div>
    <p><%= comment.body %></p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [@event, comment], data: { turbo: false }, class: 'mb-4' do |f| %>
  <%= render partial: 'partials/errors', locals: {model: comment} %>
  <div class="mb-2">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <% unless user_signed_in? %>
    <div class="mb-2">
      <%= f.label :user_name %>
      <%= f.text_field :user_name, class: 'form-control' %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit t('views.buttons.send'), class: 'btn btn-outline-primary' %>
  </div>
<% end %>