config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             skip: [:session, :password, :registration],
             controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: {
      registration: 'registrations'
    }, skip: :omniauth_callbacks

    root to: "events#index"

    resources :users, only: %i[show edit update]

    resources :events do
      resources :comments, only: %i[create destroy]
      resources :subscriptions, only: %i[create destroy]
      resources :photos, only: %i[create destroy]

      post :show, on: :member
    end
  end
  get '/politica', :to => redirect('/politica.html')
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook github]

  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  before_validation :set_name, on: :create

  after_commit :link_subscriptions, on: :create

  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true, length: { maximum: 35 }
  validates :email, length: { maximum: 255 }, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def self.find_for_facebook_oauth(access_token)
    # Достаём email из токена
    email = access_token.info.email
    user = where(email: email).first

    # Возвращаем, если нашёлся
    return user if user.present?

    # Если не нашёлся, достаём провайдера, айдишник и урл
    provider = access_token.provider
    id = access_token.extra.raw_info.id
    url = "https://facebook.com/#{id}"

    # Теперь ищем в базе запись по провайдеру и урлу
    # Если есть, то вернётся, если нет, то будет создана новая
    where(url: url, provider: provider).first_or_create! do |user|
      # Если создаём новую запись, прописываем email и пароль
      user.email = email
      user.password = Devise.friendly_token.first(16)
    end
  end

  def self.find_for_github_oauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    unless user
      user = User.create(
        email: data['email'],
        password: Devise.friendly_token[0,20]
      )
    end
    user
  end

  private

  def set_name
    self.name = "Товарисч №#{rand(777)}" if self.name.blank?
  end

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: self.email).update_all(user_id: self.id)
  end

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: 'Facebook')
      sign_in_and_redirect @user, event: :authentication
    else
      omniauth_failure
    end
  end

  def github
    @user = User.find_for_github_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Github'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.github_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  private

  def omniauth_failure
    flash[:error] = I18n.t('omniauth.failure')
    redirect_to new_user_registration_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_current_user, except: [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  private

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user)
    if user.avatar?
      user.avatar.url
    else
      asset_path('user.png')
    end
  end

  def user_avatar_thumb(user)
    if user.avatar.file.present?
      user.avatar.thumb.url
    else
      asset_path('user.png')
    end
  end
end

app/views/users/_form.html.erb
<%= form_with model: user, html: { multipart: true }, data: { turbo: false } do |f| %>
  <%= render partial: 'partials/errors', locals: { model: user } %>

  <div class="actions">
    <div class="mb-2">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="mb-2">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="mb-2">
      <%= f.label :avatar %>
      <p><%= image_tag(user.avatar.thumb.url) if user.avatar? %></p>
      <%= f.file_field :avatar %>
    </div>

    <div class="my-4">
      <%= f.submit t('views.buttons.save'), class: 'btn btn-primary' %>
    </div>
    <br>
    <%= link_to t('views.links.back'), :back %>
  </div>
<% end %>

app/views/users/_user.html.erb
<span class="user">
  <span class="user-avatar">
    <%= image_tag(user_avatar(user), class: 'img-icon') %>
  </span>
  <span class="user-name">
    <% if request.path == user_path(user) %>
      <%= user.name %>
    <% else %>
      <%= link_to user.name, user_path(user) %>
    <% end %>
  </span>
</span>

app/views/users/edit.html.erb
<div class="w-100 d-flex flex-column justify-content-center align-items-center">
  <div class="col-md-6 col-12">
    <h1 class="mt-5"><%= t('views.users.profile.editing_user') %></h1>

    <%= render "form", user: @user %>
    <div class="my-3">
      <%= link_to t('views.users.password.edit.title'), edit_user_registration_path %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center mt-5 " >
  <h1><%= @user.name %></h1>

  <%= image_tag user_avatar(@user), class: 'user-photo' %>

  <% if @user == current_user %>
    <div class="d-flex flex-row justify-content-center align-items-center mt-5 mb-5">
      <%= link_to t('views.buttons.edit_profile'), edit_user_path(@user), class: 'btn btn-outline-success me-3' %>
      <%= button_to t('views.buttons.delete_profile'), user_registration_path, method: :delete,
                    form: { data: { turbo_confirm: t('user.edit.destroy.confirm') } }, title: t('views.buttons.delete'),
                    class: 'btn btn-outline-danger me-3' %>
  <% end %>
  <%= link_to t('views.links.back'), :back, class: 'btn btn-outline-primary' %>

  </div>
  <div class="row">
    <div class="col-md-12 mt-5 text-center">
      <% if @user.events.any? %>
        <h3><%= t('views.text.user.events') %>:</h3>
        <div class="row">
          <%= render partial: 'events/event', collection: @user.events %>
        </div>
      <% else %>
        <p class="mt-5"><%= t('views.text.user.no_events') %></p>
      <% end %>
    </div>
  </div>
</div>