config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             skip: [:session, :password, :registration],
             controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: {
      registration: 'registrations'
    }, skip: :omniauth_callbacks

    root to: "events#index"

    resources :users, only: %i[show edit update]

    resources :events do
      resources :comments, only: %i[create destroy]
      resources :subscriptions, only: %i[create destroy]
      resources :photos, only: %i[create destroy]

      post :show, on: :member
    end
  end
  get '/politica', :to => redirect('/politica.html')
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  geocoded_by :address
  after_validation :geocode

  validates :user, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    ([user] + subscribers).uniq
  end

  def pincode_valid?(pin2check)
    pincode == pin2check
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_event, only: %i[destroy edit show update]
  after_action :verify_authorized, only: %i[destroy edit show update]

  def index
    @events = Event.includes(%i[user subscriptions subscribers]).all
    @coordinates = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
    end
  end

  def show
    pincode = params[:pincode] || cookies.permanent["events_#{@event.id}_pincode"]

    event_context = EventContext.new(event: @event, pincode: pincode)
    authorize event_context, policy_class: EventPolicy

    cookies.permanent["events_#{@event.id}_pincode"] = pincode

    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
    @coordinates = Gmaps4rails.build_markers(@event) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
    end

  rescue Pundit::NotAuthorizedError
    render_password_form
  end

  def new
    @event = current_user.events.build
    authorize @event
  end

  def edit
    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)
    authorize @event

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    authorize @event

    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to events_url, alert: I18n.t('controllers.events.destroyed')
  end

  private

  def render_password_form
    flash.now[:alert] = I18n.t('controllers.events.wrong_pincode') if params[:pincode].present?
    render 'password_form'
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_owner?(event)
    user_signed_in? && event.user == current_user
  end
end

app/views/events/_event.html.erb
<div class="col col-sm-6 col-md-4 p-3">
  <div class="card thumbnail">

    <%= content_tag 'div', '', class: 'event-background',
                    style: "background-image: url(#{event_thumb(event)})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="card-body">
        <div class="event-description">
          <div class="card-title">
            <h3 class="text-wrap"><%= link_to event.title, event_path(event) %></h3>
          </div>
          <div class="card-text">
            <h4><small><%= l event.datetime, format: :short %></small></h4>
            <div class="my-2"><%= link_to event.address,
                                          "https://yandex.ru/maps/?text=#{event.address}" %></div>
          </div>
        </div>
        <div>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with model: event, data: { turbo: false } do |f| %>
  <%= render partial: 'partials/errors', locals: { model: event } %>

  <div class="mb-2">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-2">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="mb-2">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="mb-2">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="mb-2">
    <%= f.label :pincode %>
    <%= f.text_area :pincode, class: 'form-control' %>
  </div>

  <div class="mb-2">
    <%= f.submit t('views.buttons.save'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1><%= t 'views.events.edit.title' %></h1>

<%= render "form", event: @event %>

<br>

<div class="container">
  <%= link_to t('views.buttons.show_event'), @event, class: 'btn btn-outline-success' %>
  <%= link_to t('views.buttons.back_to_events'), events_path, class: 'btn btn-outline-primary' %>
</div>

app/views/events/index.html.erb
<h1 class="my-5"><%= t('app.events') %></h1>

<div class="col-md-12 mb-5">
  <%= render 'partials/map' %>
</div>

<% if policy(:event).create? %>
  <%= link_to t('views.buttons.create_event'), new_event_path, class: 'btn btn-success' %>
<% end %>
<div id="events" class="my-4 row row-cols-1 row-cols-lg-3 row-cols-md-2">
  <% @events.each do |event| %>
    <%= render event %>
  <% end %>
</div>

app/views/events/new.html.erb
<h1 class="mt-3 m3"><%= t 'views.events.new.title'  %></h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render "form", event: @event %>
  </div>
</div>

<br>

<div class="container">
  <%= link_to t('views.buttons.back_to_events'), events_path, class: 'btn btn-outline-primary' %>
</div>

app/views/events/password_form.html.erb
<h2 class="mt-5"><%= t('views.text.event.pincode_title')  %></h2>

<%= form_tag(event_path(@event), method: 'post', data: { turbo: false }) do |f| %>
  <div class="mb-3">
    <%= label 'PIN', t('activerecord.attributes.event.pincode') %>
    <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
  </div>

  <div class="actions mb-3">
    <%= submit_tag t('views.buttons.send'), class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="event mt-3 d-md-flex flex-md-row flex-sm-column justify-md-content-between">
  <div class="event-info col-md-6 col-sm-12 m-sm-0 mb-sm-3 row-md m-sm-auto">
    <div class="event-photo-block p-sm-0 border border-white border-2">
      <%= content_tag 'div', '', class: 'event-background',
                      style: "background-image: url(#{event_photo(@event)})" %>

      <div class="event-info-inner m-sm-0 p-4">

        <div class="event-description pt-3">
          <h1><%= @event.title %></h1>
          <h3><%= l @event.datetime, format: :short %></h3>
          <h3><small><%= link_to @event.address,
                                 "https://yandex.ru/maps/?text=#{@event.address}" %></small></h3>
          <p><%= @event.description %></p>
        </div>
        <div class="d-flex flex-row justify-content-start align-items-center my-3">
          <% if policy(@event).edit? %>
            <%= link_to t('views.buttons.edit_event'), edit_event_path(@event),
                        class: 'btn btn-primary me-3' %>
            <%= button_to t('views.buttons.delete_event'), event_path(@event),
                          form: { data: { turbo_confirm: t('views.events.destroy.confirm') } },
                          method: :delete,
                          title: t('views.buttons.delete'),
                          class: 'btn btn-danger' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-sm-12">
    <%= render 'partials/map' %>
  </div>
</div>



<div class="row mt-5">
  <div class="col-md-8">
    <div class="event-photos mb-3">
      <div class="event-photos-gallery d-flex flex-wrap">
        <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
      </div>
      <div class="event-photo-form">
        <%= render partial: 'photos/form', locals: { photo: @new_photo || @event.photos.build } %>
      </div>
    </div>
    <div class="event-comments mt-2">
      <%= render partial: 'comments/form',
                 locals: { comment: @new_comment || @event.comments.build } %>

      <div class="mb-3">
        <%= render partial: 'comments/comment',
                   collection: @event.comments.except(@new_comment).order(created_at: :desc) %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="event-owner">
      <h4><%= t('views.text.event.calls') %>:</h4>
      <p><%= render partial: 'users/user', object: @event.user %></p>
    </div>

    <% if @event.subscriptions.size == 1 %>
      <p><%= t('views.text.event.subscribers_list') %></p>
    <% else %>
      <div class="event-subscriptions">
        <h4><%= t('views.text.event.go') %>:</h4>
        <%= render partial: 'subscriptions/subscription',
                   collection: @event.subscriptions.except(@new_subscription) %>
      </div>
    <% end %>

    <% unless event_owner?(@event) %>
      <div class="event-subscription-form">
        <h4><%= t('views.text.event.i_go') %></h4>
        <div>
          <%= render partial: 'subscriptions/form',
                     locals: { subscription: @new_subscription || @event.subscriptions.build } %>
        </div>
      </div>
    <% end %>

  </div>
</div>
<%= link_to t('views.buttons.back_to_events'), events_path, class: 'btn btn-outline-primary my-3' %>