config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             skip: [:session, :password, :registration],
             controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: {
      registration: 'registrations'
    }, skip: :omniauth_callbacks

    root to: "events#index"

    resources :users, only: %i[show edit update]

    resources :events do
      resources :comments, only: %i[create destroy]
      resources :subscriptions, only: %i[create destroy]
      resources :photos, only: %i[create destroy]

      post :show, on: :member
    end
  end
  get '/politica', :to => redirect('/politica.html')
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  with_options if: -> { user.present? } do
    validates :user, uniqueness: { scope: :event_id }
    validate :ban_subscriptions_to_own_event
  end

  with_options unless: -> { user.present? } do
    validates :user_name, presence: true
    validates :user_email, presence: true, format: /\A[a-zA-Z0-9\-_.]+@[a-zA-Z0-9\-_.]+\z/,
              uniqueness: { scope: :event_id }
    validate :cannot_use_someone_email
  end

  def user_name
    user&.name || super
  end

  def user_email
    user&.email || super
  end

  private

  def cannot_use_someone_email
    errors.add(:user_email, :wrong_email) if User.exists?(email: user_email)
  end

  def ban_subscriptions_to_own_event
    errors.add(:user_email, :creator_cant_subscribe) if event.user == user
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_event, only: %i[create destroy]
  before_action :set_subscription, only: [:destroy]

  after_action :verify_authorized, only: [:destroy]

  def create
    @new_subscription = @event.subscriptions.build(subscription_params)

    authorize @new_subscription

    @new_subscription.user = current_user

    if @new_subscription.save
      NotifySubscribersJob.perform_later(@new_subscription)
      redirect_to @event, notice: I18n.t('controllers.subscriptions.created')
    else
      render 'events/show', alert: I18n.t('controllers.subscriptions.error')
    end
  end

  def destroy
    authorize @subscription

    message = { notice: I18n.t('controllers.subscriptions.destroyed') }

    @subscription.destroy

    redirect_to @event, message
  end

  private

  def set_subscription
    @subscription = @event.subscriptions.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def subscription_params
    params.fetch(:subscription, {}).permit(:user_email, :user_name)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with model: [@event, subscription], data: { turbo: false } do |f| %>
  <%= render partial: 'partials/errors', locals: { model: subscription } %>

  <% unless user_signed_in? %>
    <div class="mb-2">
      <%= f.label :user_name %>
      <%= f.text_field :user_name, class: 'form-control' %>
    </div>

    <div class="mb-2">
      <%= f.label :user_email %>
      <%= f.text_field :user_email, class: 'form-control' %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit t('views.buttons.follow'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<div class="subscription d-flex align-items-center border-bottom border-bottom-1 py-1">
  <% if subscription.user.present? %>
    <%= render partial: 'users/user', object: subscription.user %>
  <% else %>
    <em><%= subscription.user_name %></em>
  <% end %>
  <% if policy(subscription).destroy? %>
    <%= button_to '❌', event_subscription_path(subscription.event, subscription), method: :delete,
                  form: { data: { turbo_confirm: t('.destroy_confirm') } },
                  title: t('views.buttons.delete'), class: 'btn btn-outline delete' %>
  <% end %>
</div>